/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(add.h)                                                     */
/* BINDTOOL_HEADER_FILE_HASH(ad9967cbd47cb92eb13ef1fa46e6f3f9)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cuda/add.h>
// pydoc.h is automatically generated in the build directory
// #include <add_pydoc.h> 

template <typename T>
void bind_add_template(py::module& m, const char* classname)
{
    using add = gr::cuda::add<T>;

    py::class_<add,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<add>>(m, classname)
        .def(py::init(&gr::cuda::add<T>::make),
             py::arg("num_inputs"),
             py::arg("vlen") = 1);
}

void bind_add(py::module& m)
{
    bind_add_template<std::int16_t>(m, "add_ss");
    bind_add_template<std::int32_t>(m, "add_ii");
    bind_add_template<float>(m, "add_ff");
    bind_add_template<gr_complex>(m, "add_cc");
}

