/*
 * Copyright 2026
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(fft.h)                                                     */
/* BINDTOOL_HEADER_FILE_HASH(9c6272a892ec4e591ecbbb8b20c4836c)                     */
/***********************************************************************************/

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cuda/fft.h>

void bind_fft(py::module& m)
{
    using fft = gr::cuda::fft;

    py::class_<fft,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<fft>>(m, "fft")
        .def(py::init(&gr::cuda::fft::make),
             py::arg("fft_size"),
             py::arg("forward") = true,
             py::arg("window") = std::vector<float>{},
             py::arg("shift") = false,
             py::arg("real_input") = false);
}
