/*
 * Copyright 2026 Cascade Space.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(fft_shift.h)                                               */
/* BINDTOOL_HEADER_FILE_HASH(731d39f0072bab0cfbdd7234f4120b03)                     */
/***********************************************************************************/

#include <pybind11/pybind11.h>

namespace py = pybind11;

#include <gnuradio/cuda/fft_shift.h>

void bind_fft_shift(py::module& m)
{
    using fft_shift = gr::cuda::fft_shift;

    py::class_<fft_shift,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<fft_shift>>(m, "fft_shift")
        .def(py::init(&gr::cuda::fft_shift::make),
             py::arg("fft_size"));
}
