/*
 * Copyright 2026 Cascade Space.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(streams_to_vector.h)                                       */
/* BINDTOOL_HEADER_FILE_HASH(5c414adf3d23be2eef71345f0910fad1)                                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cuda/streams_to_vector.h>

void bind_streams_to_vector(py::module& m)
{
    using streams_to_vector = gr::cuda::streams_to_vector;

    py::class_<streams_to_vector,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<streams_to_vector>>(m, "streams_to_vector")
        .def(py::init(&gr::cuda::streams_to_vector::make),
             py::arg("itemsize"),
             py::arg("num_streams"));
}

