/*
 * Copyright 2026 Cascade Space.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(stream_to_vector.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4a14b8189711c9bfc8ac01f43b405c45) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cuda/stream_to_vector.h>

void bind_stream_to_vector(py::module& m)
{
    using stream_to_vector = gr::cuda::stream_to_vector;

    py::class_<stream_to_vector,
               gr::sync_decimator,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<stream_to_vector>>(m, "stream_to_vector")
        .def(py::init(&gr::cuda::stream_to_vector::make),
             py::arg("itemsize"),
             py::arg("vlen"));
}
