/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(vector_to_stream.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c648d934023fc0639cf8862d191f39d2)                                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cuda/vector_to_stream.h>

void bind_vector_to_stream(py::module& m)
{
    using vector_to_stream = gr::cuda::vector_to_stream;

    py::class_<vector_to_stream,
               gr::sync_interpolator,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<vector_to_stream>>(m, "vector_to_stream")
        .def(py::init(&gr::cuda::vector_to_stream::make),
             py::arg("itemsize"),
             py::arg("vlen"));
}

