/* -*- c++ -*- */
/*
 * Copyright 2026 Cascade Space.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#include "seq.cuh"
#include "seq_stamp_impl.h"
#include <gnuradio/cuda/cuda_buffer.h>
#include <gnuradio/cuda/cuda_error.h>
#include <gnuradio/io_signature.h>
#include <cstdint>

namespace gr {
namespace cuda {

seq_stamp::sptr seq_stamp::make(int payload_size)
{
    return gnuradio::make_block_sptr<seq_stamp_impl>(payload_size);
}

seq_stamp_impl::seq_stamp_impl(int payload_size)
    : sync_block("seq_stamp",
                 io_signature::make(1, 1, payload_size, cuda_buffer::type),
                 io_signature::make(1, 1, payload_size + SEQ_HDR, cuda_buffer::type)),
      d_payload_size(payload_size)
{
    if (d_payload_size < 1)
        throw std::runtime_error("seq_stamp: payload_size must be >= 1");
}

int seq_stamp_impl::work(int noutput_items,
                         gr_vector_const_void_star& input_items,
                         gr_vector_void_star& output_items)
{
    auto in = static_cast<const uint8_t*>(input_items[0]);
    auto out = static_cast<uint8_t*>(output_items[0]);
    const int out_pitch = d_payload_size + SEQ_HDR;

    // Pass the input payload through, shifted past the 8-byte header slot.
    check_cuda_errors(cudaMemcpy2DAsync(out + SEQ_HDR,
                                        out_pitch,
                                        in,
                                        d_payload_size,
                                        d_payload_size,
                                        noutput_items,
                                        cudaMemcpyDeviceToDevice,
                                        d_stream),
                      "seq_stamp: cudaMemcpy2DAsync payload",
                      d_logger);

    // Prepend the incrementing sequence number into the first 8 bytes.  The
    // counter is generated by a kernel on d_stream, so there is no host
    // staging buffer to protect and thus no need to synchronize here. The
    // output is a cuda_buffer and gr-cuda's auto-sync owns the handoff.
    exec_write_seq_counters(out, out_pitch, d_counter, noutput_items, d_stream);
    check_cuda_errors(cudaGetLastError(), "seq_stamp: write_seq_counters", d_logger);

    d_counter += static_cast<uint64_t>(noutput_items);

    return noutput_items;
}

} /* namespace cuda */
} /* namespace gr */
